# Use the official PHP image with FPM support
FROM php:8.2.12-fpm

# Arguments for user
ARG user=laravel
ARG uid=1000

# Install system dependencies and Supervisor
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    nginx \
    supervisor

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create Laravel system user
RUN useradd -u ${uid} -m -s /bin/bash -g www-data ${user}

# Set working directory
WORKDIR /var/www

# Copy application code
COPY . .

# Set permissions
RUN chown -R ${user}:www-data /var/www

# Copy Supervisor and Nginx configuration
COPY docker-compose/nginx/nginx.conf /etc/nginx/nginx.conf
COPY docker-compose/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Use the Laravel user
USER ${user}

# Expose ports
EXPOSE 80 9000

# Start Supervisor (Manages PHP-FPM & Nginx)
CMD ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
