FROM php:8.2.12-fpm

# Arguments for user
ARG user=laravel
ARG uid=1000

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd

# Install PostgreSQL driver
RUN docker-php-ext-install pdo_pgsql

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user (with defined user and uid)
RUN useradd -u ${uid} -m -s /bin/bash -g www-data ${user}

# Set correct permissions for the application
COPY --chown=${user}:www-data . /var/www

USER ${user}

EXPOSE 9000

CMD ["php-fpm"]
