version: '3'

services:
  # PHP-FPM Laravel Service
  laravel_eleven_app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: laravel
        uid: 1000
    image: laravel_eleven_app_image
    container_name: laravel_eleven_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "80:80"    # Serve HTTP traffic on port 80
    networks:
      - laravel_eleven_app_network

networks:
  laravel_eleven_app_network:
    driver: bridge
