version: '3'

services:
    laravel_eleven_app:
        build:
            args:
                user: laravel_eleven_app
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel_eleven_app_image
        container_name: laravel_eleven_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel_eleven_app_network
    #nginx service
    laravel_eleven_app_webserver:
        image: nginx:alpine
        container_name: laravel_eleven_app_webserver_container
        restart: unless-stopped
        ports:
            - "6162:80"
        networks:
            - laravel_eleven_app_network

networks:
    laravel_eleven_app_network:
        driver: bridge
        
        