version: '3'

services:
    # PHP-FPM Laravel Service
    laravel_eleven_app:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                user: laravel_eleven_app
                uid: 1000
        image: laravel_eleven_app_image
        container_name: laravel_eleven_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel_eleven_app_network

    # Nginx Service
    laravel_eleven_app_webserver:
        image: nginx:alpine
        container_name: laravel_eleven_app_webserver_container
        restart: unless-stopped
        ports:
            - "9000:80" # Map 9000 to Nginx (not php-fpm)
        volumes:
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - laravel_eleven_app
        networks:
            - laravel_eleven_app_network

networks:
    laravel_eleven_app_network:
        driver: bridge
